// for generating PDFs

import PDFDocument from "pdfkit";
import { getModel } from "../utils/model.js";
import { uploadToS3 } from "../utils/uploadToS3.js";
import { getDownloadUrl } from "../utils/getDownloadUrl.js";
import { checkAgentLimit } from "../config/agentRateLimit.js";
import { deductCredits } from "../utils/deductCredits.js";

export const pdfAgent = async (state) => {

  try {
    await checkAgentLimit(state.userId, "pdf");

    await deductCredits(state.userId, "pdf");

    const llm = getModel("pdf");

    const aiResponse = await llm.invoke(`

Create a professional document about:

${state.prompt}

Rules:

- Generate a professional title.
- Generate introduction.
- Generate multiple sections.
- Generate bullet points where required.
- Generate conclusion.
- No markdown.
- No code blocks.
- No ** symbols.
- No ### headings.
- Return plain text only.

`);
 // ai returns a json response, we need to convert it to pdf using

    const rawContent = aiResponse?.content?.trim() || state.prompt;

    const lines = rawContent
      .split("\n")
      .filter(line => line.trim());

    const generatedTitle = lines?.[0]?.length < 120
        ? lines[0]
        : state.prompt;

    const cleanContent = rawContent
        .replace(/\*\*/g, "")
        .replace(/```/g, "")
        .replace(/###/g, "")
        .replace(/##/g, "")
        .replace(/#/g, "")
        .trim();

    const fileName = `pdf-${Date.now()}.pdf`;

    // create a new PDF document
    const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        bufferPages: true,
        info: {
          Title: generatedTitle,
          Author: "orbit",
          Subject: state.prompt,
          Creator: "orbit PDF Agent"
        }
      });

    const chunks = [];

    // add chunks on doc
    doc.on("data", chunk => {
      chunks.push(chunk);
    });

    // add Title
    doc
      .fontSize(26)
      .fillColor("#111827")
      .text(
        generatedTitle,
        {
          align: "center"
        }
      );

    // adds gap
    doc.moveDown();

    // add sub-title
    doc
      .fontSize(10)
      .fillColor("#6B7280")
      .text(
        `Generated on ${new Date().toLocaleString()}`,
        {
          align: "center"
        }
      );

    doc.moveDown(3);

    // add Content
    doc
      .fontSize(12)
      .fillColor("#374151")
      .text(
        cleanContent,
        {
          align: "left",
          lineGap: 6
        }
      );

    doc.moveDown(2);

    // footer
    doc
      .fontSize(10)
      .fillColor("#9CA3AF")
      .text(
        "Generated by orbit PDF Agent",
        {
          align: "center"
        }
      );

    doc.end();

    await new Promise(
      (resolve, reject) => {
        doc.on("end",resolve);
        doc.on("error",reject);
      }
    );

    // concatonate chunks
    const pdfBuffer =nBuffer.concat(chunks);

    // upload the pdf to s3
    await uploadToS3(
      pdfBuffer,
      fileName,
      "application/pdf"
    );

    // get pdf url
    const downloadUrl =
      await getDownloadUrl(
        fileName,
        24 * 60 * 60
      );

    return {
      ...state,
      response: `
# ✅ PDF Generated Successfully

📄 **${generatedTitle}**

📥 [Download PDF](${downloadUrl})

⏳ Link expires in 10 minutes.
`.trim()

    };

  } catch (error) {

    console.log(
      "PDF Agent Error:",
      error
    );
    return {
      ...state,
      response:
        "❌ Failed to generate PDF."
    };
  }
};