// for generating PDFs

import PDFDocument from "pdfkit";
import { getModel } from "../utils/model.js";
import { uploadToS3 } from "../utils/uploadToS3.js";
import { getDownloadUrl } from "../utils/getDownloadUrl.js";
import { checkAgentLimit } from "../config/agentRateLimit.js";
import { deductCredits } from "../utils/deductCredits.js";

export const pdfAgent = async (state) => {
  try {
    await checkAgentLimit(state.userId, "pdf");
    await deductCredits(state.userId, "pdf");

    const llm = getModel("pdf");
    const aiResponse = await llm.invoke(`Generate a professional document for: ${state.prompt}`);

    const rawContent = aiResponse?.content?.trim() || state.prompt;
    const lines = rawContent.split("\n").filter((l) => l.trim());
    const generatedTitle = lines?.[0]?.length < 120 ? lines[0] : state.prompt;

    const cleanContent = rawContent.replace(/\*\*/g, "").replace(/```/g, "").replace(/###/g, "").replace(/##/g, "").replace(/#/g, "").trim();

    const fileName = `pdf-${Date.now()}.pdf`;

    const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true, info: { Title: generatedTitle } });

    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));

    doc.fontSize(20).text(generatedTitle, { align: "center" });
    doc.moveDown();
    doc.fontSize(10).fillColor("#6B7280").text(`Generated on ${new Date().toLocaleString()}`, { align: "center" });
    doc.moveDown(2);
    doc.fontSize(12).fillColor("#374151").text(cleanContent, { align: "left", lineGap: 6 });
    doc.moveDown(2);
    doc.fontSize(10).fillColor("#9CA3AF").text("Generated by orbit PDF Agent", { align: "center" });

    doc.end();

    await new Promise((resolve, reject) => {
      doc.on("end", resolve);
      doc.on("error", reject);
    });

    const pdfBuffer = Buffer.concat(chunks);

    const uploadResult = await uploadToS3(pdfBuffer, fileName, "application/pdf");
    const downloadUrl = await getDownloadUrl(uploadResult.public_id || uploadResult);

    return {
      ...state,
      response: `\n# ✅ PDF Generated Successfully\n\n📄 **${generatedTitle}**\n\n📥 [Download PDF](${downloadUrl})\n\n⏳ Link expires in 10 minutes.\n`.trim(),
    };
  } catch (error) {
    console.error("PDF Agent Error:", error);
    return {
      ...state,
      response: `❌ Failed to generate PDF. Error: ${error?.message || "Unknown error"}`,
    };
  }
};